### ISSUE TITLE
No such file or directory:'model.pth'

### ISSUE THREAD

**Issue by Lucky-Xiong** [Rpeng666/FaceDetection_With_DETR#1]
Thank you for your sharing

I tried to replicate your project 

However, after I restored the environment on my computer, I got an error：

Traceback (most recent call last):
  File "D:/face_detection/face_detection_detr/FaceDetection_With_DETR-main/main.py", line 87, in <module>
    main()
  File "D:/face_detection/face_detection_detr/FaceDetection_With_DETR-main/main.py", line 28, in main
    model.load_state_dict(torch.load('./model.pth'))
  File "D:\anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './model.pth'

I can't find the file ''model.pth "in the downloaded ZIP file.

I don't know how to get this file (API？Link？)

Looking forward to your reply!

**Comment by Rpeng666** [comment]
哈哈哈，有人提issue，受宠若惊，emmm，这个是我是我学习DETR论文时随意写的，只是想弄清楚DETR到底是如何实现的，并没有写的很好。至于model嘛，感觉DETR对超参数比较敏感，我训练的model的检测确实能检测出人脸，但效果不是很好，所以没有提供。如果你想要用detr来检测人脸，可以在GitHub上搜索“detr face detection”，会有几个项目并不是从0开始训练，而是使用了预训练参数，检测效果会很不错。

Thank you for your watching. This project is simply and casually completed for the purpose of learning DETR . The performance of model I trained was not very good, so I didn't provide the model file.  I think the reason is probably poor dataset, sensitivity to hyperparameters etc. If you want use detr model for high accuracy face detection, you can search "detr face detection" in github. There are serveral projects which train model with pretrained parameters . I think the performance is excellent.
